name: qlphongtro_tenant
description: Ứng dụng mobile quản lý phòng trọ dành cho người thuê
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # UI & Navigation
  cupertino_icons: ^1.0.2
  go_router: ^12.1.3
  flutter_screenutil: ^5.9.0
  
  # State Management
  provider: ^6.1.1
  
  # HTTP & API
  http: ^1.1.0
  dio: ^5.4.0
  
  # Local Storage
  shared_preferences: ^2.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  # Image & Media
  cached_network_image: ^3.3.0
  image_picker: ^1.0.4
  
  # Utils
  intl: ^0.19.0
  uuid: ^4.2.1
  permission_handler: ^11.1.0
  
  # Charts & Analytics
  fl_chart: ^0.66.0
  
  # Notifications
  flutter_local_notifications: ^16.3.2
  
  # Maps & Location
  geolocator: ^10.1.0
  google_maps_flutter: ^2.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.7

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
    - assets/logos/
  
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700

